### ISSUE TITLE
Scripts not loading.

### ISSUE THREAD

**Issue by BlazeApple** [KospY/BasSDK#39] opened 2022-08-24 21:49 UTC
No matter what I do the scripts wont load. Error Message - "The associated script can not be loaded. Please fix any compile errors and assign valid script." I have confirmed with other modders that I have everything good and they have no clue why.

**Comment by KaiDevvy** [comment] 2022-08-25 18:15
This seems to be a common issues that's popping up for users, more information is needed to reproduce it consistently.

Were you following any particular tutorial? Can you describe how you installed the SDK? Are you using any third party packages or third party modding tools?

**Comment by BlazeApple** [comment] 2022-08-25 19:38
Nope, I just installed the sdk downloaded the new unity version and boom. I asked Piepop101 to help and he didnt know the issue

**Comment by DragsWF** [comment] 2022-08-25 19:38
Are you on Unity Version 2020.3.33?

**Comment by BlazeApple** [comment] 2022-08-25 19:51
Yes. I did it on a seperate computer with the same process and it worked there no clue why

**Comment by KaiDevvy** [comment] 2022-08-30 23:55
So after looking into a few reports of this issue, it looks like packages are failing to install correctly. Pre-initialized versions of the SDK seem to work fine for users having this issue, so certainly something going wrong during first time startup.
Some examples of the errors that are stopping compilation:

![image](https://user-images.githubusercontent.com/18744053/187563070-3e0b1a41-430d-4ba4-95f4-fc2d3cca0568.png)
![image](https://user-images.githubusercontent.com/18744053/187563087-9041b605-d94c-42bc-8c39-d334821101aa.png)
![image](https://user-images.githubusercontent.com/18744053/187563097-1cd30753-ff0e-4d46-927d-5594fcc13a5d.png)
![image](https://user-images.githubusercontent.com/18744053/187563102-cb578764-cacd-499c-ac80-a78a966c42b8.png)

This seems to be a rare Unity problem unrelated to the SDK, so it's probably safe to close this issue.

Potentially caused by:
- Antivirus/Firewall breaking Unity package installation
- Corrupt installation of Unity 2020.3.33f1
- Insufficient disk space

**Closed** 2022-09-08 08:59 UTC
